### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by mcpcpc** [mcpcpc/kirc#12]
# todo

**Important**: Requests will only be considered if filed as a [Feature Request](https://github.com/mcpcpc/kirc/issues/new/choose). 

If you would like to contribute to platform verification, feel free to post a comment (or contact me on _#kisslinux_ or _#kirc_ IRC channels) explaining the steps that you took to verify program functionality, as well as the procedure to install `kirc` on the target platform.

- [x] Add command to bypass local commands for communicating directly with the IRC server. (https://github.com/mcpcpc/kirc/commit/c6c68710ee2a6bafa18b8c53bf648fbd827c8416)
- [x] Add `NAMES` commands for listing users (and status) of the current channel. (https://github.com/mcpcpc/kirc/commit/58f98487747c8871dbc7c2e40573d81fe0beeaf7)
- [x] Eliminate instances of `sscanf`.
- [x] Markdown version of `README` for improved readability. (https://github.com/mcpcpc/kirc/commit/ddb4105344622f170b036f23bc97fd93a3c901f6)
- [x] Remove annoying leading whitespace char. (https://github.com/mcpcpc/kirc/commit/77428d93d72c04b22807c4d769399a83ee366c7b)
- [x] ~~Change default behavior of arrow and CTRL keys.~~ _No change at this time since this would require creating a custom text editor._
- [x] ~~Add hard wrap for strings exceeding the max specified character columns (e.g. long URLs).~~ _No change. Decided against this as this makes copy-paste from a terminal window more difficult._  
- [x] Create *#kirc* IRC channel for users to test functionality and set as default channel at initial connection.
- [x] Add a private message channel indicator for messages sent for those joined after initial connection. (https://github.com/mcpcpc/kirc/commit/92cec2c0fab534981e00edfdd88420baafacb694)
- [x] Add argument to pass commands at initial connection. (https://github.com/mcpcpc/kirc/commit/5ff7c4db553958c8afe61a3d04f84301cd97c84a)
- [x] Add basic argument for printing basic usage information. (https://github.com/mcpcpc/kirc/commit/9f769eac6136707489c0d2e4a743491a74b48fc1)
- [x] Improve error handling and report _errno_. (https://github.com/mcpcpc/kirc/commit/2dd79499209b7179278dfbf2e3c8843c987e244b)
- [x] ~~Relax requirements from C99 to C89.~~  _Not entertaining this as part of the master branch as POSIX specifies `c99`._
- [x] Add a way to switch the default message channel.  (https://github.com/mcpcpc/kirc/commit/35f8d5b5738c676460af60bb5621b380da4dbd73)
- [x] Add shortcut command for `/h` to print available commands.  (https://github.com/mcpcpc/kirc/commit/90c6d716283fb9305426ea04341aa44b1f79f9ac)
- [x] colorize channel name when message recieved from a channel other than the one set as default. (https://github.com/mcpcpc/kirc/commit/47ca652d6c75debbd266af4580223c63682337de)
- [x] ~~*Consider* adding TLS/SSL support.~~ _will never be added since functionality can be achieved using third-party tools._ (https://github.com/mcpcpc/kirc/commit/7587814cdf34c86ec4bb2ee6f080943b72db6863)
- [x] log_append() doesn't check fopen return value. (https://github.com/mcpcpc/kirc/commit/fe395f9385cf5313eb3479a6595477bdc6fab0b4)
- [x] “$ ./kirc Nick not specified: Success” should return failed (https://github.com/mcpcpc/kirc/commit/faabd1e7bef412f9bf90bbcce30a7a4845c2cb0d)
- [x] Disable CTRL and arrow keys from printing to `stdin`. _Not fixed. See https://github.com/mcpcpc/kirc/issues/24 for rationale._
- [x] Make `stdin` blocking.  __update: this appears to be only doable by entering raw mode, which is something i have managed to avoid thus far.__ (https://github.com/mcpcpc/kirc/commit/7eec954a21cb185b1f8561f55ddd1ec8f2f88bc1)
- [x] Add command line flag to force ipv6 support. _not fully implemented but it will no longer force IPv4. calling it closed for now as i would like to minimize command line arguments._ (https://github.com/mcpcpc/kirc/commit/0b0087074ea6d273bc58733280f38465f870c35e)
- [ ] Dynamically allocate cmd_str variable
- [x] Add argument option to pass multiple channels for automatic joining (other than the initial one) (https://github.com/mcpcpc/kirc/commit/e5afb77d2143063183396a8c3679db238823039d)
- [ ] Add automatic nickname coloring.
- [ ] write() should check for EINTR&EAGAIN (https://github.com/mcpcpc/kirc/commit/d95e2a74ed7eebd2f76e2ad366f92f2cbedcd296)
- [ ] connect() errors should print where they failed to connect.
- [ ] Add support for CTCP ACTION
- [ ] Investigate `kirc `peformance on additional Unix distributions:
    - KISS Linux (installs and functional)
    - Raspbian (installs and functional)
    - Arch Linux (available in AUR, not tested though)
    - Mint Linux (not tested)
    - Debian (not tested)
    - Windows WSL (informed that commands may not be functioning)
- [ ] fix segmentation fault on no internet connection.

**Comment by mcpcpc** [comment]
Closing as this will be tracked via the _todo_ kanban on the "Projects" tab.
